data:
  num_samples: 10000
  input_shape: [116, 116]
  num_classes: 2
  batch_size: 8
  k_fold: 10

model:
  num_heads: 128
  key_dim: 2
  dropout: 0.9

training:
  epochs: 100
  learning_rate: 0.01
  loss: "binary_crossentropy"
  optimizer: "adam"
  metrics: ["accuracy"]
  min_epochs_before_save: 10         # Minimum number of epochs before model saving

device:
  use_gpu: false

random_seed: 7777
